### ISSUE TITLE
MerkleBranch not generated

### ISSUE THREAD

**Issue by zhangbincheng1997** [bitcoin-core/btcdeb#101]
Makefile.am not write relevant code.
but see the relevant code in the historical version : [5bf8c0467530a1827f8197f0a5a78bf559322ffa](https://github.com/bitcoin-core/btcdeb/tree/5bf8c0467530a1827f8197f0a5a78bf559322ffa)
yes, it work. but the result is different from your blog.....

https://medium.com/@kallewoof/trying-out-mast-merkelized-abstract-syntax-trees-1c6459fb2b47
![image](https://user-images.githubusercontent.com/18366691/146676293-0fbc9963-750b-49d3-916c-d883703057d6.png)

![image](https://user-images.githubusercontent.com/18366691/146676286-ff495e19-00a4-4466-b241-02ac38c4fdb9.png)

Thanks, waiting for your answer

**Comment by zhangbincheng1997** [comment]
And when i use this proof, an error occurred.
`./btcdeb '[TOALTSTACK 4cae2f5573c5728f37f1a610ff01f8f4adba6474e71d5a50c1354292d04e74a4 OP_2 MERKLEBRANCHVERIFY 2DROP DROP]' '[FROMALTSTACK OP_4 EQUAL]' 00016fd3be48f92d23c4fca81284b450df859271f863d11ab6dd5795b5ce08548691 04`

![image](https://user-images.githubusercontent.com/18366691/146676390-16ea59aa-e2e4-47f3-981c-3f2f6cb28314.png)

**Comment by kallewoof** [comment]
Sorry for the misleading article. That one is outdated. Please check out https://github.com/bitcoin-core/btcdeb/blob/master/doc/tapscript-example-with-tap.md instead, for now.

**Comment by zhangbincheng1997** [comment]
Thanks, this is very useful for me!
