### ISSUE TITLE
Mockvalues produce an error: invalid pubkey pub1

### ISSUE THREAD

**Issue by mplsgrant** [bitcoin-core/btcdeb#106]
The example found in the [Inline operators](https://github.com/bitcoin-core/btcdeb/blob/master/doc/mock-values.md#inline-operators) section of mock-values.md produces the following error: 

    $ ./btcdeb '[OP_2 OP_DROP sig1 pub1 OP_DUP OP_HASH160 hash160(pub1) OP_EQUALVERIFY OP_CHECKSIG]' --pretend-valid=sig1:pub1
    btcdeb 0.3.20 -- type `./btcdeb -h` for start up options
    notice: btcdeb has gotten quieter; use --verbose if necessary (this message is temporary)
    invalid pubkey pub1

**Comment by kallewoof** [comment]
Sorry about that. The clean-up of old code resulted in breaking this feature. It's been fixed, thanks for the report!

Please reply here if it doesn't work still on latest master.

**Comment by mplsgrant** [comment]
I recompiled from master, and the issue seems to remain. Perhaps I am missing a step in the process?

    $ ./btcdeb '[OP_2 OP_DROP sig1 pub1 OP_DUP OP_HASH160 hash160(pub1) OP_EQUALVERIFY OP_CHECKSIG]' --pretend-valid=sig1:pub1
    btcdeb 0.4.22 -- type `./btcdeb -h` for start up options
    LOG: signing segwit taproot
    notice: btcdeb has gotten quieter; use --verbose if necessary (this message is temporary)
    invalid pubkey pub1

**Comment by kallewoof** [comment]
What does the top of `git log` say? It should be commit e8c2750c4a4702768c52d15640ed03bf744d2601.

Your line works on my end on master.

**Comment by mplsgrant** [comment]
As suspected, I did not have the correct version. It works now. Thanks!
