### ISSUE TITLE
Unable to build on Mac

### ISSUE THREAD

**Issue by Conrad0000** [bitcoin-core/btcdeb#110]
Make command seems to begin failing at `ld: warning: ignoring file libbitcoin.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )`
Exits with
`clang: error: linker command failed with exit code 1`...
`make[1]: *** [btcdeb] Error 1
make: *** [all-recursive] Error 1`

Also notable is this warning in autogen.sh:

`configure.ac:36: warning: The macro 'AC_PROG_CC_C89' is obsolete. `

Full output attached.
[output.txt](https://github.com/bitcoin-core/btcdeb/files/8621186/output.txt)

**Comment by kallewoof** [comment]
What kind of mac is this? New (M1)?

You seem to be building for valgrind. Is that intentional?

I just tried a clean compile from scratch and it worked fine. Can you show me a complete log of all your steps (from `./autogen.sh` call all the way to `make`)?

**Comment by kallewoof** [comment]
Closing due to lack of information. Will reopen if/when more info on build setup is provided.
