### ISSUE TITLE
Docker container fails to run

### ISSUE THREAD

**Issue by kzhunter** [bitcoin-core/btcdeb#126]
Docker image builds without any issue, but the container fails to start when I try to run it.

Running `docker logs btc-vm` or starting the container interactively shows me the following the error.

> btcdeb: line 1: syntax error: unexpected word (expecting ")")

**Comment by kallewoof** [comment]
I believe latest master fixes this. Let me know if that's not the case.

**Comment by kzhunter** [comment]
It's working now.
