### ISSUE TITLE
How to get input hex for --txin= ?

### ISSUE THREAD

**Issue by panicfarm** [bitcoin-core/btcdeb#131]
This is more of a request for clarification of the [btcdeb.md](https://github.com/bitcoin-core/btcdeb/blob/master/doc/btcdeb.md).
In the usecase of `btcdeb --tx=<tx hex> --txin=<txin hex>`, how does one obtain the hex of the input of interest? In the example there:
```
$ btcdeb --tx=010000000001019086ce64fce1bb086395faf6fac37c73f32ba4ea89330432bf8ee8035e9315aa0100000000ffffffff021353b9030000000017a914c3f413d0918853a8e23766678d2e3c2e5c8138bb8725e4973100000000220020701a8d401c84fb13e6baf169d59684e17abd9fa216c8cc5b9fc63d622ff8c58d040047304402207f874ef00f11dcc9a621acad9354f3fca1bf90c43878f607b7e2d358088487e7022052a01b47b8eef5e1c96a6affdc3dac46fdc11b60612464dc8c5921a852090d2701483045022100c56ab2abb17fdf565417228763bc9f2940a6465042fd62fbd9f4c7406345d7f702201cb1a56b45181f8347713627b325ec5df48fc1aee6bdaf937cbb804d7409b10c016952210375e00eb72e29da82b89367947f29ef34afb75e8654f6ea368e0acdfd92976b7c2103a1b26313f430c4b15bb1fdce663207659d8cac749a0e53d70eff01874496feff2103c96d495bfdd5ba4145e3e046fee45e84a8a48ad05bd8dbb395c011a32cf9f88053ae00000000 \
txin=0100000000010170a6ee35199eae2d8ea659561374fa704f8fd95188ff5931157e4598dd0c44020100000000ffffffff0280f0fa02000000001976a914eec426a744f7a3b2ffd346925ac832e248834dd788ac4013543500000000220020701a8d401c84fb13e6baf169d59684e17abd9fa216c8cc5b9fc63d622ff8c58d04004730440220054c0b331a31496d9123aeabe8415b8d2f877f1cf67709120af4eb1e09de59e002206cdf84e733e23be531aff202f868d200773e22aa0037033a74fc6752df2fd19601483045022100b54fa12828d13b58cb654dd910b9e8b36d471d644d8f66516577990ca099ee19022048ea2ac78f964d1b823af70c13c5607a29b14bb2348022190b3c280f51ec5df2016952210375e00eb72e29da82b89367947f29ef34afb75e8654f6ea368e0acdfd92976b7c2103a1b26313f430c4b15bb1fdce663207659d8cac749a0e53d70eff01874496feff2103c96d495bfdd5ba4145e3e046fee45e84a8a48ad05bd8dbb395c011a32cf9f88053ae00000000 
```
the hex of the txin (`0100000000010170a...`, 383Bytes) is actually longer than the hex for the whole tx itself (`010000000001019...`, 381Bytes). How was the hex for txin obtained?

When I run `bitcoin-cli decoderawtransaction <txin hex>` to see what txin hex is, it gives full JSON of the whole transaction, same as running `bitcoin-cli decoderawtransaction <tx hex>`

**Comment by kallewoof** [comment]
Some explorers allow you to see the raw hex value of a transaction, rather than seeing its "decoded" form. 

Bitcoin-cli has a getrawtransaction command which lets you do this as well. If you know the block hash as well, you can use this to get the transaction hex value by doing
```
bitcoin-cli getrawtransaction <TXIN TXID> <TXIN CONTAINED BLOCK HASH>
```

**Comment by panicfarm** [comment]
> Some explorers allow you to see the raw hex value of a transaction, rather than seeing its "decoded" form.
> 
> Bitcoin-cli has a getrawtransaction command which lets you do this as well. If you know the block hash as well, you can use this to get the transaction hex value by doing
> 
> ```
> bitcoin-cli getrawtransaction <TXIN TXID> <TXIN CONTAINED BLOCK HASH>
> ```

Thanks, my confusion was that `--txin=<reftx hex>` is the hex of the _entire_ referenced transaction, that the input is referencing. Perhaps it should be clarified in [btcdeb.md](https://github.com/bitcoin-core/btcdeb/blob/master/doc/btcdeb.md), it was unclear. 

I still do not understand, if the `--tx=<hex>` has more than one input that reference the _same_ `--txin=<reftx hex>`, which tx's input script btcdeb is going to debug?

**Comment by kallewoof** [comment]
If `tx` is spending multiple inputs in `txin`, you have to select the input index you want to look at using the `-s` (`--select`) flag. Otherwise btcdeb will derive the first input being spent and pick that.

**Comment by panicfarm** [comment]
Perhaps it's worth adding an example with all three `--tx=<hex> --txin=<hex> --select=<input no>`  into [btcdeb.md](https://github.com/bitcoin-core/btcdeb/blob/master/doc/btcdeb.md). I can look for a representative transaction and submit a PR, if you think it's useful.

Another question: 
A script verification (most often) involves verification of (pubKey, signature) pairs, given the sighash. Is there an API to btcdeb that allows to return all (pubKey, signature) pairs, that have been successfully verified for a given input script (regardless of the script logic)? Or is there a way to link to Bitcoin core to get this functionality?

**Comment by kallewoof** [comment]
> Perhaps it's worth adding an example with all three `--tx=<hex> --txin=<hex> --select=<input no>` into [btcdeb.md](https://github.com/bitcoin-core/btcdeb/blob/master/doc/btcdeb.md). I can look for a representative transaction and submit a PR, if you think it's useful. I also did a [screen grab](https://www.youtube.com/watch?v=_BhewoIOWco) illustrating how btcdeb works for a non-trivial script.

Yeah, sounds like a good thing to have.

> Another question:
> 
> A script verification (most often) involves verification of (pubKey, signature) pairs, given the sighash. Is there an API to btcdeb that allows to return all (pubKey, signature) pairs, that have been successfully verified for a given input script (regardless of the script logic)? Or, in the absence of a btcdeb API, perhaps linking to Bitcoin Core libraries and calling its C++ functions is a way to get the verified (pubKey, signature) pairs, given tx, txin and the input number?
> 
> This is the screenshot from btcdeb of what I am looking for: ![pubkeys](https://user-images.githubusercontent.com/8865628/249925886-66460dbd-1496-4709-8bf2-432af58f5257.png)

Nope, no such functionality at the moment.
