### ISSUE TITLE
error: Using OP_CODESEPARATOR in non-witness script

### ISSUE THREAD

**Issue by panicfarm** [bitcoin-core/btcdeb#139]
I am trying to verify transaction [`055707ce7fea7b9776fdc70413f65ceec413d46344424ab01acd5138767db137 input 1`](https://blockstream.info/tx/055707ce7fea7b9776fdc70413f65ceec413d46344424ab01acd5138767db137?expand) with

```
btcdeb -s 1 --tx=3000000:0100000002cbbc32acfd347fcc5b2466974c12be20eb15495be50b8b6dfa3e4e88c0823beb000000006a47304402205e9e74f93f6aa1b095bbe124be0be95aeca52ebe91f214c86febe512b26c827c0220379ee83416df7c2adc753b5eefe61e7aef10ec208b549a249b6006e8009a0e210121031dd6da443782f1099b0ed98060b9ee1b81cd2392e938d23015749625c7dd0470ffffffffcbbc32acfd347fcc5b2466974c12be20eb15495be50b8b6dfa3e4e88c0823beb010000007000483045022013187aed1aeaaca0ca8a7c0e4f6362070208e68a5230c7a3cf65d922da19964802210082ac0719fd2be6c40b550791a96449e6bf1f70ed9492f88e825416c099d36b2601ab51210232abdc893e7f0631364d7fd01cb33d24da45329a00357b3a7886211ab414d55a51aeffffffff02903a1c00000000001976a914f7d46c08dd53bc6bbb52178d60b3fc99a9c1fb8788acc0c62d000000000017142a9bc5447d664c1d0141392a842d23dba45c4f13b17500000000 --txin=01000000024de8b0c4c2582db95fa6b3567a989b664484c7ad6672c85a3da413773e63fdb8000000006b48304502205b282fbc9b064f3bc823a23edcc0048cbb174754e7aa742e3c9f483ebe02911c022100e4b0b3a117d36cab5a67404dddbf43db7bea3c1530e0fe128ebc15621bd69a3b0121035aa98d5f77cd9a2d88710e6fc66212aff820026f0dad8f32d1f7ce87457dde50ffffffff4de8b0c4c2582db95fa6b3567a989b664484c7ad6672c85a3da413773e63fdb8010000006f004730440220276d6dad3defa37b5f81add3992d510d2f44a317fd85e04f93a1e2daea64660202200f862a0da684249322ceb8ed842fb8c859c0cb94c81e1c5308b4868157a428ee01ab51210232abdc893e7f0631364d7fd01cb33d24da45329a00357b3a7886211ab414d55a51aeffffffff02e0fd1c00000000001976a914380cb3c594de4e7e9b8e18db182987bebb5a4f7088acc0c62d000000000017142a9bc5447d664c1d0141392a842d23dba45c4f13b17500000000
```

It's an old transaction that has a signature in the output with the `OP_CODESEPARATOR`  followed by 1 of 1 multisig, and an `OP_CHECKLOCKTIMEVERIFY` in the spending input.
I get `error: Using OP_CODESEPARATOR in non-witness script`. Here is the [screen grab](https://youtu.be/D3FKNQNXQlw) of the error.

**Comment by kallewoof** [comment]
Try with `--modify-flags="-CONST_SCRIPTCODE"`.

You will find that you also need to add `-LOW_S` i.e. `--modify-flags="-CONST_SCRIPTCODE,-LOW_S"`.

Even with that, your `OP_CHECKLOCKTIMEVERIFY` is hitting a number overflow. Looks like it is getting `2a9bc5447d664c1d0141392a842d23dba45c4f13` as its argument, which is definitely higher than what you would expect from a number.

**Comment by panicfarm** [comment]
> --modify-flags="-CONST_SCRIPTCODE,-LOW_S"

This worked, thanks. I will close it

**Comment by panicfarm** [comment]
--modify-flags="-CONST_SCRIPTCODE,-LOW_S" solved it
