### ISSUE TITLE
Linux installation issue

### ISSUE THREAD

**Issue by adam-harry** [bitcoin-core/btcdeb#142]
Apologies if this is an obvious query - I am relative novice with linux, this is first time I've tried to build anything from source (I assume that's what I'm doing with the 'make' command)

I have installed the dependencies but am running into the error below.

I have the source files in my downloads folder, should I move them elsewhere?

>adam@server:~/downloads/btcdeb/btcdeb-0.3.20$ make
make[1]: Entering directory '/home/adam/downloads/btcdeb/btcdeb-0.3.20'
make[2]: Entering directory '/home/adam/downloads/btcdeb/btcdeb-0.3.20/secp256k1'
make[2]: Leaving directory '/home/adam/downloads/btcdeb/btcdeb-0.3.20/secp256k1'
  CXX      test/btcdeb-test-btcdeb.o
In file included from /usr/include/signal.h:328,
                 from test/catch.hpp:6113,
                 from test/test-btcdeb.cpp:3:
test/catch.hpp:8749:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
 8749 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from test/catch.hpp:6113,
                 from test/test-btcdeb.cpp:3:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from test/test-btcdeb.cpp:3:
test/catch.hpp:8808:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 8808 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
make[1]: *** [Makefile:1479: test/btcdeb-test-btcdeb.o] Error 1
make[1]: Leaving directory '/home/adam/downloads/btcdeb/btcdeb-0.3.20'
make: *** [Makefile:1536: all-recursive] Error 1

**Comment by kallewoof** [comment]
I have no idea why you would be getting that error. Can you write down the steps you took to install the dependencies? Also, what distro is this?

**Comment by adam-harry** [comment]
Hi there, I'm using Ubuntu 22.04.4 LTS

I used these commends:

sudo apt-get install libtool libssl-dev autoconf pkg-config
./autogen.sh
./configure
make

Do I need to move the downloaded folder somewhere for it to work?

**Comment by kallewoof** [comment]
Ohh, it looks like newer compilers changed something which broke catch2. Thanks, looking now.

**Comment by kallewoof** [comment]
I believe this has been fixed now. Can you try pulling and trying again?

(Oh, and you don't need to move the files if you don't want to. I would recommend creating a `workspace` folder in your home dir and putting things like this in there, though, but it's 100% personal preference.)

**Comment by adam-irving** [comment]
Yup works now - thanks very much for looking into this for me!
