### ISSUE TITLE
Mac installation additionally requires brew install automake

### ISSUE THREAD

**Issue by yvonneCh** [bitcoin-core/btcdeb#70]
Setup instructions as is leads to an error message on `./autogen.sh`

```
autoreconf: failed to run aclocal
```

According to this issue: https://github.com/buffer/pylibemu/issues/24, it's due to missing `aclocal`, which can be added to my path with `brew install automake`. 

Suggestion to modify the README as follows

`brew install libtool autoconf pkg-config` -> `brew install libtool autoconf pkg-config automake`

**Comment by kallewoof** [comment]
Thanks, yes this is correct. Patch incoming.

**Comment by kallewoof** [comment]
(Btw, automake depends on autoconf so no need to include both in the brew install command)
