### ISSUE TITLE
Taproot addresses are encoded bech32 instead of bech32m

### ISSUE THREAD

**Issue by brandonblack** [bitcoin-core/btcdeb#86]

**Comment by kallewoof** [comment]
I think this will be resolved when I upgrade to latest Bitcoin Core code base. Will prioritize that.

**Comment by kallewoof** [comment]
Sorry this was quite delayed. I'm looking into an issue with tap tool right now, but should have something into master soon.

**Comment by kallewoof** [comment]
Let me know if this was not resolved and I'll reopen this issue. (Or file a new one.)
