### ISSUE TITLE
Running `make` shows error missing `#include <cstring>` in file `strencodings.h`

### ISSUE THREAD

**Issue by Dimianovic** [bitcoin-core/btcdeb#91]
I just tried to `make` btcdeb and I got the following error: 

```
make[1]: Entering directory '/home/standup/btcdeb'
  CXX      util/libbitcoin_a-strencodings.o
In file included from util/strencodings.cpp:6:
./util/strencodings.h: In function ‘bool ValidAsCString(const string&)’:
./util/strencodings.h:31:26: error: ‘strlen’ was not declared in this scope
   31 |     return str.size() == strlen(str.c_str());
      |                          ^~~~~~
./util/strencodings.h:17:1: note: ‘strlen’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   16 | #include <iterator>
  +++ |+#include <cstring>
   17 | #include <string>
make[1]: *** [Makefile:1345: util/libbitcoin_a-strencodings.o] Error 1
make[1]: Leaving directory '/home/standup/btcdeb'
make: *** [Makefile:1626: all-recursive] Error 1

```

After this I simple included `#include <cstring>` in the file `./util/strencodings.h` and I ran fine.

Please fix :)

**Comment by Dimianovic** [comment]
Strange, I just wanted to create a pull request but there already is cstring included in the code. Closing this.

**Comment by unencode** [comment]
Same thing happened to me, it looks like  #include <cstring> is commented out in strencodings.h on latest git repo.

**Comment by kallewoof** [comment]
@unencode @Dimianovic Thanks, I double checked and you're right that it doesn't compile on linux. The CI tests are broken so I didn't notice, as I primarily work on a mac. Fix in master.
