### ISSUE TITLE
Error during installation in Fedora 33

### ISSUE THREAD

**Issue by ltola** [bitcoin-core/btcdeb#96]
During the installation in Fedora 33 (uname -r -> 5.12.8-200.fc33.x86_64 ), in particular during _make_ command I get the following error:

_**[luca@localhost btcdeb]$ make
make[1]: ingresso nella directory «/home/luca/Documenti/software/btcdeb»
  CXX      util/libbitcoin_a-strencodings.o
In file included from util/strencodings.cpp:6:
./util/strencodings.h: In function ‘bool ValidAsCString(const string&)’:
./util/strencodings.h:31:26: error: ‘strlen’ was not declared in this scope
   31 |     return str.size() == strlen(str.c_str());
      |                          ^~~~~~
./util/strencodings.h:17:1: note: ‘strlen’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   16 | #include <iterator>
  +++ |+#include <cstring>
   17 | #include <string>
make[1]: *** [Makefile:1343: util/libbitcoin_a-strencodings.o] Errore 1
make[1]: uscita dalla directory «/home/luca/Documenti/software/btcdeb»
make: *** [Makefile:1624: all-recursive] Errore 1**_

Can you solve this  issue?
Tnkyou

**Comment by kallewoof** [comment]
Can you try on latest master? I recently fixed an issue similar to this.

**Comment by ltola** [comment]
Solved by installing the latest master.
